defaults:
    - scope:
          type: pages
      values:
          layout: page
    - scope:
          type: posts
      values:
          layout: post
exclude:
    - package.json
    - design
gems:
    - jekyll-paginate
paginate: 10
paginate_path: /:num
url: https://noyainrain.github.io
title: noyainrain.github.io
description: Sven's personal website.
# States if I am available for hire. true means I'm currently available, false means I'm not and a
# string means I'm only available at a later time (given by the string, e.g. 'summer' or
# 'June 2017').
available: May 2017
